
"use server";

import { revalidatePath } from "next/cache";
import { createProduct as dbCreateProduct, updateProduct as dbUpdateProduct, deleteProduct as dbDeleteProduct } from "@/lib/products";
import type { Product } from "@/lib/types";
import { generateSlug } from "@/lib/utils";

const constructProductData = (formData: FormData): Partial<Omit<Product, 'id' | 'images' | 'slug'>> => {
    const data: Partial<Omit<Product, 'id' | 'images' | 'slug'>> = {
        paymentMobileNumber: formData.get('paymentMobileNumber') as string || undefined,
        name: formData.get('name') as string,
        brand: formData.get('brand') as string,
        price: Number(formData.get('price')),
        stock: Number(formData.get('stock')),
        description: formData.get('description') as string,
        condition: formData.get('condition') as Product['condition'],
        featured: false,
        tags: (formData.get('tags') as string || '').split(',').map(tag => tag.trim()).filter(Boolean),
        fullSpecsGsmArena: formData.get('fullSpecsGsmArena') as string || '',
        categories: {
            gamingPerformance: formData.get('categories.gamingPerformance') as Product['categories']['gamingPerformance'],
            camera: formData.get('categories.camera') as Product['categories']['camera'],
            battery: formData.get('categories.battery') as Product['categories']['battery'],
            looksAndFeel: formData.get('categories.looksAndFeel') as Product['categories']['looksAndFeel'],
            valueForMoney: formData.get('categories.valueForMoney') as Product['categories']['valueForMoney'],
        },
        specs: {
            network: formData.get('specs.network') as string || '',
            dimensions: formData.get('specs.dimensions') as string || '',
            weight: formData.get('specs.weight') as string || '',
            build: formData.get('specs.build') as string || '',
            sim: formData.get('specs.sim') as string || '',
            display: {
                type: formData.get('specs.display.type') as string || '',
                size: formData.get('specs.display.size') as string || '',
                resolution: formData.get('specs.display.resolution') as string || '',
                protection: formData.get('specs.display.protection') as string || '',
            },
            platform: {
                os: formData.get('specs.platform.os') as string || '',
                chipset: formData.get('specs.platform.chipset') as string || '',
                cpu: formData.get('specs.platform.cpu') as string || '',
                gpu: formData.get('specs.platform.gpu') as string || '',
            },
            memory: {
                ram: formData.get('specs.memory.ram') as string || '',
                storage: formData.get('specs.memory.storage') as string || '',
                card_slot: formData.get('specs.memory.card_slot') as string || '',
            },
            mainCamera: {
                modules: formData.get('specs.mainCamera.modules') as string || '',
                features: formData.get('specs.mainCamera.features') as string || '',
                video: formData.get('specs.mainCamera.video') as string || '',
            },
            selfieCamera: {
                modules: formData.get('specs.selfieCamera.modules') as string || '',
                features: formData.get('specs.selfieCamera.features') as string || '',
                video: formData.get('specs.selfieCamera.video') as string || '',
            },
            sound: {
                loudspeaker: formData.get('specs.sound.loudspeaker') as string || '',
                jack_3_5mm: formData.get('specs.sound.jack_3_5mm') as string || '',
            },
            features: (formData.get('specs.features') as string || '').split(',').map(f => f.trim()).filter(Boolean),
            battery: {
                type: formData.get('specs.battery.type') as string || '',
                charging: formData.get('specs.battery.charging') as string || '',
            }
        },
    };

    const originalPrice = formData.get('originalPrice');
    if (originalPrice) {
        data.originalPrice = Number(originalPrice);
    }

    const batteryHealth = formData.get('batteryHealth');
    if (batteryHealth) {
        data.batteryHealth = batteryHealth as string;
    }
    
    return data;
};


export async function createProduct(formData: FormData) {
  const imagesString = formData.get('images') as string;
  const images = imagesString ? JSON.parse(imagesString) : [];

  const data = constructProductData(formData);
  const productData: Partial<Omit<Product, 'id' | 'slug'>> = { ...data, images: images };
  
  // A temporary ID for slug generation. The final ID will be generated by Firestore.
  const tempId = Math.random().toString(36).substring(2, 9);
  const slug = generateSlug(data.name!, tempId);

  await dbCreateProduct(productData as Omit<Product, 'id' | 'slug'>, slug);
  revalidatePath('/admin/products');
  revalidatePath('/products');
}


export async function updateProduct(id: string, formData: FormData) {
  const data = constructProductData(formData);
  const slug = generateSlug(data.name!, id);
  const productData: Partial<Product> = { ...data, slug };

  const imagesString = formData.get('images') as string;
  if (imagesString) {
    productData.images = JSON.parse(imagesString);
  }

  await dbUpdateProduct(id, productData);
  revalidatePath('/admin/products');
  revalidatePath(`/products/${slug}`);
}


export async function deleteProduct(id: string) {
  await dbDeleteProduct(id);
  revalidatePath('/admin/products');
  revalidatePath('/');
}
